on: [push, pull_request]

name: Check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} check

    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'macOS-10.15', 'ubuntu-20.04' ]
        r: [ 'release' ]

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}

      - uses: s-u/R-actions/pkg-check@master
        with:
          debian-deps: libssl-dev
          macos-deps: pkgconfig-0.28 openssl-1.1.1h
          check-flags: --as-cran
